---
title: "attribute plots"
output: html_document
date: '2022-04-25'
---
## innitialization
```{r} 
library("ggplot2")
library('dplyr')
```

```{r}
## plot of sigCluste unsupervised mRNA

Basallike_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Basal-like') %>% 
  count(`SigClust Unsupervised mRNA`) %>% mutate('PAM50' = 'Basal-like')

LuminalA_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal A') %>% 
  count(`SigClust Unsupervised mRNA`) %>% mutate('PAM50' = 'Luminal A')

LuminalB_count= BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal B') %>% 
  count(`SigClust Unsupervised mRNA`) %>%  mutate('PAM50' = 'Luminal B')

HER2enriched_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'HER2-enriched') %>% 
  count(`SigClust Unsupervised mRNA`) %>%  mutate('PAM50' = 'HER2-enriched')

statistic = rbind(Basallike_count ,LuminalA_count,
                 LuminalB_count,HER2enriched_count)


ggplot(statistic,aes(x = `SigClust Unsupervised mRNA`,
             y = n, fill=PAM50)) +geom_col()
```
```{r}
## plot of miRNA Clusters

Basallike_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Basal-like') %>% 
  count(`miRNA Clusters`) %>% mutate('PAM50' = 'Basal-like')

LuminalA_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal A') %>% 
  count(`miRNA Clusters`) %>% mutate('PAM50' = 'Luminal A')

LuminalB_count= BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal B') %>% 
  count(`miRNA Clusters`) %>%  mutate('PAM50' = 'Luminal B')

HER2enriched_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` =='HER2-enriched') %>% 
  count(`miRNA Clusters`) %>%  mutate('PAM50' = 'HER2-enriched')

statistic = rbind(Basallike_count ,LuminalA_count,
                 LuminalB_count,HER2enriched_count)


ggplot(statistic,aes(x = `miRNA Clusters`,
             y = n, fill=PAM50)) +geom_col()
```
```{r}
## plot of sigCluste unsupervised mRNA

Basallike_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Basal-like') %>% 
  count(`SigClust Intrinsic mRNA`) %>% mutate('PAM50' = 'Basal-like')

LuminalA_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal A') %>% 
  count(`SigClust Intrinsic mRNA`) %>% mutate('PAM50' = 'Luminal A')

LuminalB_count= BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal B') %>% 
  count(`SigClust Intrinsic mRNA`) %>%  mutate('PAM50' = 'Luminal B')

HER2enriched_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'HER2-enriched') %>% 
  count(`SigClust Intrinsic mRNA`) %>%  mutate('PAM50' = 'HER2-enriched')

statistic = rbind(Basallike_count ,LuminalA_count,
                 LuminalB_count,HER2enriched_count)


ggplot(statistic,aes(x = `SigClust Intrinsic mRNA`,
             y = n, fill=PAM50)) +geom_col()
```
```{r}
## plot of methylation Clusters

Basallike_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Basal-like') %>% 
  count(`methylation Clusters`) %>% mutate('PAM50' = 'Basal-like')

LuminalA_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal A') %>% 
  count(`methylation Clusters`) %>% mutate('PAM50' = 'Luminal A')

LuminalB_count= BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal B') %>% 
  count(`methylation Clusters`) %>%  mutate('PAM50' = 'Luminal B')

HER2enriched_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'HER2-enriched') %>% 
  count(`methylation Clusters`) %>%  mutate('PAM50' = 'HER2-enriched')

statistic = rbind(Basallike_count ,LuminalA_count,
                 LuminalB_count,HER2enriched_count)


ggplot(statistic,aes(x = `methylation Clusters`,
             y = n, fill=PAM50)) +geom_col()
```
```{r}
## plot of `Integrated Clusters (with PAM50)`

Basallike_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Basal-like') %>% 
  count(`Integrated Clusters (with PAM50)`) %>% mutate('PAM50' = 'Basal-like')

LuminalA_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal A') %>% 
  count(`Integrated Clusters (with PAM50)`) %>% mutate('PAM50' = 'Luminal A')

LuminalB_count= BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal B') %>% 
  count(`Integrated Clusters (with PAM50)`) %>%  mutate('PAM50' = 'Luminal B')

HER2enriched_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'HER2-enriched') %>% 
  count(`Integrated Clusters (with PAM50)`) %>%  mutate('PAM50' = 'HER2-enriched')

statistic = rbind(Basallike_count ,LuminalA_count,
                 LuminalB_count,HER2enriched_count)


ggplot(statistic,aes(x = `Integrated Clusters (with PAM50)`,
             y = n, fill=PAM50)) +geom_col()
```

```{r}
## plot of Integrated Clusters (no exp)

Basallike_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Basal-like') %>% 
  count(`Integrated Clusters (no exp)`) %>% mutate('PAM50' = 'Basal-like')

LuminalA_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal A') %>% 
  count(`Integrated Clusters (no exp)`) %>% mutate('PAM50' = 'Luminal A')

LuminalB_count= BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal B') %>% 
  count(`Integrated Clusters (no exp)`) %>%  mutate('PAM50' = 'Luminal B')

HER2enriched_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'HER2-enriched') %>% 
  count(`Integrated Clusters (no exp)`) %>%  mutate('PAM50' = 'HER2-enriched')

statistic = rbind(Basallike_count ,LuminalA_count,
                 LuminalB_count,HER2enriched_count)


ggplot(statistic,aes(x = `Integrated Clusters (no exp)`,
             y = n, fill=PAM50)) +geom_col()
```
```{r}
## plot of Integrated Clusters (unsup exp)

Basallike_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Basal-like') %>% 
  count(`Integrated Clusters (unsup exp)`) %>% mutate('PAM50' = 'Basal-like')

LuminalA_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal A') %>% 
  count(`Integrated Clusters (unsup exp)`) %>% mutate('PAM50' = 'Luminal A')

LuminalB_count= BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'Luminal B') %>% 
  count(`Integrated Clusters (unsup exp)`) %>%  mutate('PAM50' = 'Luminal B')

HER2enriched_count = BC_Data %>% filter(BC_Data$`PAM50 mRNA` == 'HER2-enriched') %>% 
  count(`Integrated Clusters (unsup exp)`) %>%  mutate('PAM50' = 'HER2-enriched')

statistic = rbind(Basallike_count ,LuminalA_count,
                 LuminalB_count,HER2enriched_count)


ggplot(statistic,aes(x = `Integrated Clusters (unsup exp)`,
             y = n, fill=PAM50)) +geom_col()
```

